### ISSUE TITLE
SyntaxError: Invalid regular expression: /^\/p\/(.*)\/(?(?:([^\/]+?))){0,1}subscribe=(.*)\/?$/: Invalid group

### ISSUE THREAD

**Issue by antoviaque** [JohnMcLear/ep_email_notifications#23]
With the latest etherpad-lite (v1.5.6, git sha: 0a9c631):

```
[2015-05-02 11:23:25.156] [ERROR] console - SyntaxError: Invalid regular expression: /^\/p\/(.*)\/(?(?:([^\/]+?))){0,1}subscribe=(.*)\/?$/: Invalid group
    at new RegExp (<anonymous>)
    at pathtoRegexp (/home/etherpad/etherpad-lite/src/node_modules/express/node_modules/path-to-regexp/index.js:69:10)
    at new Layer (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/layer.js:32:17)
    at Function.proto.route (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:482:15)
    at EventEmitter.app.(anonymous function) [as get] (/home/etherpad/etherpad-lite/src/node_modules/express/lib/application.js:464:30)
    at Object.exports.registerRoute [as hook_fn] (/home/etherpad/etherpad-lite/node_modules/ep_email_notifications/index.js:11:12)
    at normalizedhook (/home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /home/etherpad/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Function._.map._.collect (/home/etherpad/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
```

**Comment by JohnMcLear** [comment]
Confirmed

**Comment by JohnMcLear** [comment]
Lots of shit appears to be broken, I will try to take a look this week.

@quenenni perhaps you can take a look too?

**Comment by antoviaque** [comment]
@JohnMcLear Thank you! : )

**Comment by JohnMcLear** [comment]
Fixed and published working version
